In [93]:
import numpy as np
import pandas as pd
from __future__ import print_function


In [94]:
path = 'D:\ml-data\dataset\ml-100k\\'
u_cols = ['user_id','age','sex','occupation','zip_code']
users = pd.read_csv(path + 'u.user',sep = '|',names = u_cols)
n_users = users.shape[0]
'number of n user {}.'.format(n_users)


'number of n user 943.'

In [95]:
f'users : {n_users}'

'users : 943'

In [96]:
r_cols = ['user_id','movie_id','rating','unix_timestamp']
ratings_base = pd.read_csv(path + 'ua.base',sep = '\t',names = r_cols)
ratings_test = pd.read_csv(path + 'ua.test',sep='\t',names = r_cols)

print(ratings_base)

       user_id  movie_id  rating  unix_timestamp
0            1         1       5       874965758
1            1         2       3       876893171
2            1         3       4       878542960
3            1         4       3       876893119
4            1         5       3       889751712
...        ...       ...     ...             ...
90565      943      1047       2       875502146
90566      943      1074       4       888640250
90567      943      1188       3       888640250
90568      943      1228       3       888640275
90569      943      1330       3       888692465

[90570 rows x 4 columns]


In [97]:
rate_train = np.asmatrix(ratings_base)
rate_train

matrix([[        1,         1,         5, 874965758],
        [        1,         2,         3, 876893171],
        [        1,         3,         4, 878542960],
        ...,
        [      943,      1188,         3, 888640250],
        [      943,      1228,         3, 888640275],
        [      943,      1330,         3, 888692465]], dtype=int64)

In [98]:
rate_test = np.asmatrix(ratings_test)

In [99]:
print(f'numbers of training rates:{rate_base.shape[0]}')
f'numbers of testing rates: {rate_test.shape[0]}'

numbers of training rates:90570


'numbers of testing rates: 9430'

In [100]:
# Structuring product information
i_cols = ['movie id', 'movie title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure', 'Animation', 'Children\'s',
'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
items = pd.read_csv(path + 'u.item',sep = '|',encoding='latin-1',names = i_cols)
items

movie id                                movie title release date  \
0            1                           Toy Story (1995)  01-Jan-1995   
1            2                           GoldenEye (1995)  01-Jan-1995   
2            3                          Four Rooms (1995)  01-Jan-1995   
3            4                          Get Shorty (1995)  01-Jan-1995   
4            5                             Copycat (1995)  01-Jan-1995   
...        ...                                        ...          ...   
1677      1678                          Mat' i syn (1997)  06-Feb-1998   
1678      1679                           B. Monkey (1998)  06-Feb-1998   
1679      1680                       Sliding Doors (1998)  01-Jan-1998   
1680      1681                        You So Crazy (1994)  01-Jan-1994   
1681      1682  Scream of Stone (Schrei aus Stein) (1991)  08-Mar-1996   

      video release date                                           IMDb URL  \
0                    NaN  http://us.imdb.com/M/title-exact?Toy%20Story%2...   
1                    NaN  http://us.imdb.com/M/title-exact?GoldenEye%20(...   
2                    NaN  http://us.imdb.com/M/title-exact?Four%20Rooms%...   
3                    NaN  http://us.imdb.com/M/title-exact?Get%20Shorty%...   
4                    NaN  http://us.imdb.com/M/title-exact?Copycat%20(1995)   
...                  ...                                                ...   
1677                 NaN  http://us.imdb.com/M/title-exact?Mat%27+i+syn+...   
1678                 NaN  http://us.imdb.com/M/title-exact?B%2E+Monkey+(...   
1679                 NaN      http://us.imdb.com/Title?Sliding+Doors+(1998)   
1680                 NaN  http://us.imdb.com/M/title-exact?You%20So%20Cr...   
1681                 NaN  http://us.imdb.com/M/title-exact?Schrei%20aus%...   

      unknown  Action  Adventure  Animation  Children's  ...  Fantasy  \
0           0       0          0          1           1  ...        0   
1           0       1          1          0           0  ...        0   
2           0       0          0          0           0  ...        0   
3           0       1          0          0           0  ...        0   
4           0       0          0          0           0  ...        0   
...       ...     ...        ...        ...         ...  ...      ...   
1677        0       0          0          0           0  ...        0   
1678        0       0          0          0           0  ...        0   
1679        0       0          0          0           0  ...        0   
1680        0       0          0          0           0  ...        0   
1681        0       0          0          0           0  ...        0   

      Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
0             0       0        0        0        0       0         0    0   
1             0       0        0        0        0       0         1    0   
2             0       0        0        0        0       0         1    0   
3             0       0        0        0        0       0         0    0   
4             0       0        0        0        0       0         1    0   
...         ...     ...      ...      ...      ...     ...       ...  ...   
1677          0       0        0        0        0       0         0    0   
1678          0       0        0        0        1       0         1    0   
1679          0       0        0        0        1       0         0    0   
1680          0       0        0        0        0       0         0    0   
1681          0       0        0        0        0       0         0    0   

      Western  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
1677        0  
1678        0  
1679        0  
1680        0  
1681        0  

[1682 rows x 24 columns]

In [101]:
X0 = np.asmatrix(items)
X_train_counts = X0[:,-19:]
X_train_counts

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 1, 1, ..., 1, 0, 0],
        [0, 0, 0, ..., 1, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=object)

In [102]:
print(rate_train[:4])

[[        1         1         5 874965758]
 [        1         2         3 876893171]
 [        1         3         4 878542960]
 [        1         4         3 876893119]]


In [103]:
#tfidf
from sklearn.feature_extraction.text import TfidfTransformer
transformer = TfidfTransformer(smooth_idf=True,norm = 'l2')
X1 = transformer.fit(np.asarray(X_train_counts))
X = np.asarray(X_train_counts)
X[1,:]


array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
      dtype=object)

In [104]:
rate_train[1,2]

3

In [139]:
def get_items_rated_by_user(rate_matrix,user_id):
    y = rate_matrix[:,0] # get all user
    # item indices rated by user_id
    # we need to +1 to user_id since in the rate_matrix, id starts from 1
    # but id in python starts from 0
    ids = np.where(y==user_id+1)[0]
    
    item_ids = rate_matrix[ids,1]-1
    scores = rate_matrix[ids,2]
    return (item_ids.reshape(-1).tolist()[0],scores.reshape(-1).tolist()[0])


In [111]:
get_items_rated_by_user(rate_train,2)

(matrix([[180],
         [257],
         [259],
         [263],
         [267],
         [270],
         [271],
         [287],
         [298],
         [299],
         [301],
         [302],
         [306],
         [316],
         [317],
         [318],
         [319],
         [320],
         [321],
         [323],
         [324],
         [325],
         [326],
         [328],
         [329],
         [332],
         [335],
         [337],
         [338],
         [339],
         [340],
         [341],
         [343],
         [344],
         [345],
         [346],
         [347],
         [348],
         [349],
         [350],
         [351],
         [352],
         [353],
         [354]], dtype=int64),
 matrix([[4],
         [2],
         [4],
         [2],
         [3],
         [3],
         [2],
         [2],
         [3],
         [2],
         [2],
         [3],
         [3],
         [2],
         [4],
         [2],
         [5],
         [5],
         [3],
         [2],
 

In [131]:
ids,scores = get_items_rated_by_user(rate_train,1)
np.asarray(ids)

print(scores.reshape(-1).tolist()[0])
Xhat = X[ids[0],:]
Xhat

[4, 2, 4, 3, 4, 5, 4, 5, 4, 5, 4, 4, 3, 4, 5, 4, 3, 5, 4, 4, 3, 4, 4, 5, 4, 5, 4, 3, 3, 3, 3, 4, 1, 4, 3, 3, 4, 4, 4, 5, 4, 4, 3, 4, 3, 3, 1, 4, 5, 5, 1, 5]


array([[[0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]],
      dtype=object)

In [114]:
print(X.shape[1])

19


In [140]:
# find weight of coef
from sklearn.linear_model import Ridge
from sklearn import linear_model
d = X.shape[1]
W = np.zeros((d,n_users))
b = np.zeros(n_users)
for n in range(n_users):
    (ids,scores) = get_items_rated_by_user(rate_train,n)
  

    model = Ridge(alpha=0.01,fit_intercept=True)
    Xhat = X[ids,:]
    model.fit(Xhat,scores)
    W[:,n] = model.coef_
    b[n] = model.intercept_

In [141]:
Yhat = X.dot(W) + b
n = 10
np.set_printoptions(precision=2) # 2 digits after .
ids, scores = get_items_rated_by_user(rate_test, n)
print('Rated movies ids :', ids )
print('True ratings :', scores)
print('Predicted ratings:', Yhat[ids, n])
"""Rated movies ids : [ 37 109 110 226 424 557 722 724 731 739]
True ratings : [3 3 4 3 4 3 5 3 3 4]
Predicted ratings: [3.18 3.13 3.42 3.09 3.35 5.2 4.01 3.35 3.42 3.72]"""


Rated movies ids : [37, 109, 110, 226, 424, 557, 722, 724, 731, 739]
True ratings : [3, 3, 4, 3, 4, 3, 5, 3, 3, 4]
Predicted ratings: [3.178632469570199 2.9570842918322215 3.4024255625477813
 3.0502454415218785 3.392863763422993 5.196497621466598 3.9272023855358635
 3.392863763422993 3.4024255625477813 3.7755936902565006]


'Rated movies ids : [ 37 109 110 226 424 557 722 724 731 739]\nTrue ratings : [3 3 4 3 4 3 5 3 3 4]\nPredicted ratings: [3.18 3.13 3.42 3.09 3.35 5.2 4.01 3.35 3.42 3.72]'

In [142]:
def evaluate(Yhat, rates, W, b):
    se = cnt = 0
    for n in range(n_users):
        ids, scores_truth = get_items_rated_by_user(rates, n)
        scores_pred = Yhat[ids, n]
        e = scores_truth - scores_pred
        se += (e*e).sum(axis = 0)
        cnt += e.size
    return np.sqrt(se/cnt)
print('RMSE for training: %.2f' %evaluate(Yhat, rate_train, W, b))
print('RMSE for test : %.2f' %evaluate(Yhat, rate_test, W, b))
"""RMSE for training: 0.91
RMSE for test : 1.27"""

RMSE for training: 0.91
RMSE for test : 1.28


'RMSE for training: 0.91\nRMSE for test : 1.27'